//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "one_time_passwords")]
pub struct Model {
    #[sea_orm(unique)]
    pub id: Uuid,
    pub token: Option<String>,
    pub created_at: Option<DateTime>,
    pub expired_at: Option<DateTime>,
    pub is_expired: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_information::Entity")]
    UserInformation,
}

impl Related<super::user_information::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserInformation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
