//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::access_tokens::Entity as AccessTokens;
pub use super::one_time_passwords::Entity as OneTimePasswords;
pub use super::user_information::Entity as UserInformation;
