//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use super::sea_orm_active_enums::AccountStatus;
use super::sea_orm_active_enums::Gender;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_information")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub middle_name: Option<String>,
    pub username: Option<String>,
    pub email: Option<String>,
    pub password: Option<String>,
    pub account_status: Option<AccountStatus>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub last_available_at: Option<DateTime>,
    pub full_name: Option<String>,
    pub otp_id: Option<String>,
    pub phone_number: Option<String>,
    pub gender: Option<Gender>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
